
<field:name itemname="姓名" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:name>

<field:email itemname="邮箱" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:email>

<field:mobile itemname="电话" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:mobile>

<field:company itemname="公司名称" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:company>

<field:content itemname="需求描述" autofield="1" type="multitext" isnull="true" default=""  maxlength="250" page="">
</field:content>
