<dl>
          <dd style="background:url([field:litpic/]) no-repeat center center; background-size:cover;"><a href="[field:arcurl/]"></a></dd>
          <dt>
            <h3><a href="[field:arcurl/]">[field:title/]</a></h3>
          </dt>
          <dt>[field:typename/]   [field:pubdate function='strftime("%Y-%m-%d",@me)'/]</dt>
          <dt>[field:description function='cn_substr(@me,200)'/]...</dt>
        </dl>