<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="2";
$z[1]=Array("img"," /uploads/allimg/160429/1-160429153Z4.jpg ",93,261);
$z[1][4]['ddimg']="/uploads/allimg/160429/1-160429153Z4.jpg";
$z[1][4]['text']="优品汇手机助手";
$z[1][4]['width']="2560";
$z[1][4]['height']="1000";
$z[2]=Array("img"," /uploads/allimg/160429/1-160429153Z4-50.jpg ",263,437);
$z[2][4]['ddimg']="/uploads/allimg/160429/1-160429153Z4-50.jpg";
$z[2][4]['text']="优品汇手机助手";
$z[2][4]['width']="2560";
$z[2][4]['height']="1000";
$z[3]=Array("img"," /uploads/allimg/160429/1-160429153Z4-51.jpg ",439,613);
$z[3][4]['ddimg']="/uploads/allimg/160429/1-160429153Z4-51.jpg";
$z[3][4]['text']="优品汇手机助手";
$z[3][4]['width']="2560";
$z[3][4]['height']="1000";
$z[4]=Array("img"," /uploads/allimg/160429/1-160429153Z4-52.jpg ",615,789);
$z[4][4]['ddimg']="/uploads/allimg/160429/1-160429153Z4-52.jpg";
$z[4][4]['text']="优品汇手机助手";
$z[4][4]['width']="2560";
$z[4][4]['height']="1000";

?>