<dl >
        <dd style="background:url([field:litpic/]) no-repeat center center; background-size:cover;"><a href="[field:arcurl/]"></a></dd>
        <dt>
          <h2><a href="[field:arcurl/]">[field:title/]</a></h2>
        </dt>
        <dt>[field:typename/]   [field:pubdate function='strftime("%Y-%m-%d",@me)'/]</dt>
        <dt>[field:description function='cn_substr(@me,50)'/]......<a href="[field:arcurl/]" class="bt">查看全文</a></dt>
      </dl>