<?php
$z[0]=Array("field","",212,231);
$z[0][4]['name']="title";
$z[1]=Array("global","",232,258);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",299,321);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",361,412);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",1550,1585);
$z[4][4]['filename']="head.htm";
$z[5]=Array("productimagelist"," \r\n        <div class=\"jise_big\" style=\"background:url([field:imgsrc/]) no-repeat center top;background-size:cover;\"></div>\r\n        ",1711,1891);
$z[6]=Array("field","",2014,2033);
$z[6][4]['name']="title";
$z[7]=Array("field","",2056,2074);
$z[7][4]['name']="body";
$z[8]=Array("arclist","\r\n        <dl>\r\n          <dd style=\"background:url([field:litpic/]) no-repeat center top; background-size:cover;\"><a href=\"[field:arcurl/]\"></a></dd>\r\n          <dt>\r\n            <h3><a href=\"[field:arcurl/]\">[field:title/]</a></h3>\r\n          </dt>\r\n          <dt>[field:description function='cn_substr(@me,70)'/]...</dt>\r\n        </dl>\r\n        ",3020,3430);
$z[8][4]['row']="3";
$z[8][4]['titlelen']="36";
$z[8][4]['typeid']="5";
$z[9]=Array("global","",4022,4049);
$z[9][4]['name']="cfg_basehost";
$z[10]=Array("field","",4050,4077);
$z[10][4]['name']="arcurl";
$z[11]=Array("include","",4417,4452);
$z[11][4]['filename']="foot.htm";

?>