<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="2";
$z[1]=Array("img"," /uploads/allimg/160429/1-160429201J0.jpg ",93,266);
$z[1][4]['ddimg']="/uploads/allimg/160429/1-160429201J0.jpg";
$z[1][4]['text']="微健智能跑步机应用";
$z[1][4]['width']="2560";
$z[1][4]['height']="780";
$z[2]=Array("img"," /uploads/allimg/160429/1-160429201J0-50.jpg ",268,447);
$z[2][4]['ddimg']="/uploads/allimg/160429/1-160429201J0-50.jpg";
$z[2][4]['text']="微健智能跑步机应用";
$z[2][4]['width']="2560";
$z[2][4]['height']="800";
$z[3]=Array("img"," /uploads/allimg/160429/1-160429201J0-51.jpg ",449,628);
$z[3][4]['ddimg']="/uploads/allimg/160429/1-160429201J0-51.jpg";
$z[3][4]['text']="微健智能跑步机应用";
$z[3][4]['width']="2560";
$z[3][4]['height']="800";
$z[4]=Array("img"," /uploads/allimg/160429/1-160429201J0-52.jpg ",630,809);
$z[4][4]['ddimg']="/uploads/allimg/160429/1-160429201J0-52.jpg";
$z[4][4]['text']="微健智能跑步机应用";
$z[4][4]['width']="2560";
$z[4][4]['height']="800";
$z[5]=Array("img"," /uploads/allimg/160429/1-160429201J0-53.jpg ",811,990);
$z[5][4]['ddimg']="/uploads/allimg/160429/1-160429201J0-53.jpg";
$z[5][4]['text']="微健智能跑步机应用";
$z[5][4]['width']="2560";
$z[5][4]['height']="800";

?>