<?php
$z[0]=Array("type","<h1>[field:typename /]</h1>",333,395);
$z[0][4]['typeid']="10";
$z[1]=Array("type","<h1>[field:typename /]</h1>",870,931);
$z[1][4]['typeid']="5";
$z[2]=Array("channel","\r\n          <li><a href='[field:typeurl/]'>[field:typename/]</a></li>\r\n          ",960,1092);
$z[2][4]['type']="son";
$z[2][4]['typeid']="5";
$z[3]=Array("type","<h1>[field:typename /]</h1>",1165,1226);
$z[3][4]['typeid']="2";
$z[4]=Array("channel","\r\n          <li><a href='[field:typeurl/]'>[field:typename/]</a></li>\r\n          ",1255,1387);
$z[4][4]['type']="son";
$z[4][4]['typeid']="2";
$z[5]=Array("type","<h1>[field:typename /]</h1>",1460,1522);
$z[5][4]['typeid']="11";
$z[6]=Array("channel","\r\n          <li><a href='[field:typeurl/]'>[field:typename/]</a></li>\r\n          ",1551,1684);
$z[6][4]['type']="son";
$z[6][4]['typeid']="11";
$z[7]=Array("global","",1824,1845);
$z[7][4]['name']="cfg_yx";
$z[8]=Array("global","",1873,1894);
$z[8][4]['name']="cfg_sj";
$z[9]=Array("global","",1922,1943);
$z[9][4]['name']="cfg_dh";
$z[10]=Array("global","",1973,1994);
$z[10][4]['name']="cfg_qq";
$z[11]=Array("global","",2040,2061);
$z[11][4]['name']="cfg_qq";
$z[12]=Array("global","",2166,2187);
$z[12][4]['name']="cfg_dz";
$z[13]=Array("flink","[field:link /]",2275,2323);
$z[13][4]['row']="24";
$z[14]=Array("global","",2338,2364);
$z[14][4]['name']="cfg_powerby";
$z[15]=Array("global","",2365,2389);
$z[15][4]['name']="cfg_beian";

?>