<?php
$z[0]=Array("global","",211,237);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",281,311);
$z[1][4]['name']="cfg_description";
$z[2]=Array("global","",348,375);
$z[2][4]['name']="cfg_keywords";
$z[3]=Array("include","",1559,1594);
$z[3][4]['filename']="head.htm";
$z[4]=Array("arclist","\r\n      <div class=\"rsContent\"><a><img class=\"rsImg\" src=\"[field:litpic/]\"/></a></div>\r\n      ",1726,1883);
$z[4][4]['row']="5";
$z[4][4]['titlelen']="36";
$z[4][4]['typeid']="15";
$z[5]=Array("channel","\r\n        <a href='[field:typeurl/]'>[field:typename/]</a> / \r\n        ",2680,2802);
$z[5][4]['type']="son";
$z[5][4]['typeid']="5";
$z[6]=Array("arclist","\r\n        <dl>\r\n          <dd style=\"background:url([field:litpic/]) no-repeat center top; background-size:cover;\"> <a href=\"[field:arcurl/]\" title=\"Jackery app\"></a> </dd>\r\n        </dl>\r\n       ",2866,3124);
$z[6][4]['row']="9";
$z[6][4]['titlelen']="36";
$z[6][4]['typeid']="5";
$z[7]=Array("type","<a href=\"[field:typeurl/]#templatemo4\">咨询我们</a> <a href=\"[field:typeurl/]\">了解更多</a>",6081,6214);
$z[7][4]['typeid']="1";
$z[8]=Array("arclist","\r\n      <dl>\r\n        <dd style=\"background:url([field:litpic/]) no-repeat center center; background-size:cover;\"> <a href=\"[field:arcurl/]\" title=\"[field:title/]\"></a> </dd>\r\n        <dt>[field:description function='cn_substr(@me,120)'/]...</dt>\r\n      </dl>\r\n      ",6424,6753);
$z[8][4]['row']="6";
$z[8][4]['titlelen']="36";
$z[8][4]['typeid']="2";
$z[9]=Array("include","",7634,7669);
$z[9][4]['filename']="foot.htm";

?>